"""Browsable HTML for entity profiles, served by the same dashboard.

The markdown files stay the source of truth — agents read and write them
directly — and this is a view over them, re-read on every request so a profile
edited by hand or regenerated by a build shows up without a restart.

Rendered semantically rather than as generic markdown: the abstract, the sample
systems and the timeline mean different things and earn different treatment. The
timeline in particular distinguishes monthly entries from yearly ones, because
that difference is the whole point of the rolling resolution — recent months are
detail, older years are summary, and a reader should see which they are looking
at.
"""

from __future__ import annotations

import html
from typing import Any

from aiohttp import web

from slackqa.profiles import INSTRUMENT, PERSON, Profile, Profiles

CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { margin:0; padding:2rem 1rem 4rem; background:#fbfbfc; color:#1a1c20;
  font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; }
.wrap { max-width:52rem; margin:0 auto; }
a { color:#2f6fd0; text-decoration:none; }
a:hover { text-decoration:underline; }
h1 { font-size:1.5rem; margin:0 0 .3rem; }
h2.sec { font-size:.78rem; text-transform:uppercase; letter-spacing:.09em;
  color:#8a9099; margin:2.2rem 0 .7rem; font-weight:700; }
.sub { color:#71777f; font-size:.88rem; margin:0 0 1.8rem; }
.crumb { font-size:.85rem; margin-bottom:1.2rem; }

.card { background:#fff; border:1px solid #e4e6ea; border-radius:10px;
  padding:.9rem 1.05rem; margin-bottom:.6rem; }
.card .row { display:flex; align-items:baseline; gap:.6rem; flex-wrap:wrap; }
.card .name { font-weight:650; font-size:1.02rem; }
.card .blurb { color:#5d636b; font-size:.9rem; margin-top:.3rem;
  display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical;
  overflow:hidden; }

.tag { font-size:.68rem; font-weight:700; letter-spacing:.04em; padding:.14rem .5rem;
  border-radius:999px; text-transform:uppercase; }
.ok { background:#e6f4ec; color:#1a7f45; }
.prov { background:#fdf2e2; color:#9a6512; }
.dormant { background:#eef0f2; color:#6b7280; }
.kindtag { background:#eaf0fb; color:#3a5f9e; }

.abstract { font-size:1.02rem; }
.abstract p { margin:0 0 .8rem; }
.systems { display:flex; flex-wrap:wrap; gap:.35rem; }
.chip { background:#eef1f5; color:#3b4351; border-radius:6px; padding:.2rem .5rem;
  font-size:.82rem; font-variant-numeric:tabular-nums; }

.entry { display:grid; grid-template-columns:5.5rem 1fr; gap:1rem;
  padding:.75rem 0; border-top:1px solid #ececf0; }
.period { font-variant-numeric:tabular-nums; font-weight:650; font-size:.86rem;
  color:#4a5058; }
.period .grain { display:block; font-weight:400; font-size:.7rem; color:#9aa0a8; }
.entry.year .period { color:#8a9099; }
.meta { color:#8a9099; font-size:.82rem; margin-top:1.6rem; }
.empty { color:#8a9099; font-style:italic; }

.actions { display:flex; gap:.5rem; align-items:center; margin:1.2rem 0 0; }
button, .btn { font:inherit; font-size:.86rem; padding:.4rem .8rem; border-radius:7px;
  border:1px solid #d3d7dd; background:#fff; color:#2a2f36; cursor:pointer; }
button:hover { background:#f4f6f8; }
button.primary { background:#2f6fd0; border-color:#2f6fd0; color:#fff; }
button.primary:hover { background:#2a63ba; }
input[type=text], textarea { font:inherit; width:100%; padding:.5rem .6rem;
  border:1px solid #d3d7dd; border-radius:7px; background:#fff; color:#1a1c20; }
textarea { min-height:9rem; resize:vertical; line-height:1.55; }
.panel { border:1px solid #e4e6ea; background:#fff; border-radius:10px;
  padding:1rem; margin-top:1rem; }
.panel label { display:block; font-size:.78rem; text-transform:uppercase;
  letter-spacing:.06em; color:#8a9099; font-weight:700; margin:.8rem 0 .3rem; }
.panel label:first-child { margin-top:0; }
.warn { background:#fdf2e2; border:1px solid #f0dcb8; color:#7a5410;
  border-radius:8px; padding:.6rem .8rem; font-size:.85rem; margin-bottom:1.2rem; }
.hist { font-size:.82rem; color:#8a9099; margin-top:.5rem; }
.hidden { display:none; }
.entry .prov { display:flex; gap:.5rem; align-items:center; margin-top:.45rem;
  font-size:.78rem; color:#8a9099; flex-wrap:wrap; }
.entry .prov button { font-size:.74rem; padding:.15rem .5rem; border-radius:5px; }
.mini { margin-top:.5rem; }
.mini textarea { min-height:5.5rem; font-size:.9rem; }
.mini .actions { margin-top:.5rem; }
.mini input[type=text] { max-width:16rem; }
.tick { color:#1a7f45; font-weight:650; }

@media (prefers-color-scheme: dark) {
  body { background:#111316; color:#e7e9ec; }
  .card { background:#181b1f; border-color:#292d33; }
  .card .blurb, .sub, .meta, .empty { color:#98a0aa; }
  h2.sec, .period .grain { color:#7b838d; }
  .chip { background:#22262c; color:#c2c8d0; }
  .entry { border-color:#24282e; }
  a { color:#79a9f0; }
  .ok { background:#14331f; color:#71cf95; }
  .prov { background:#372c14; color:#dcb055; }
  .dormant { background:#23262b; color:#9aa1aa; }
  .kindtag { background:#1c2534; color:#8fb0e6; }
  button, .btn { background:#1c1f24; border-color:#31363d; color:#e0e3e8; }
  button:hover { background:#242830; }
  button.primary { background:#2f6fd0; border-color:#2f6fd0; color:#fff; }
  input[type=text], textarea { background:#15181c; border-color:#31363d; color:#e7e9ec; }
  .panel { background:#181b1f; border-color:#292d33; }
  .warn { background:#33270f; border-color:#5a4718; color:#e0bd6a; }
  .tick { color:#71cf95; }
}
"""


def _page(title: str, body: str) -> web.Response:
    doc = (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"<title>{html.escape(title)}</title><style>{CSS}</style></head>"
        f'<body><div class="wrap">{body}</div></body></html>'
    )
    return web.Response(text=doc, content_type="text/html")


def _paras(text: str) -> str:
    blocks = [b.strip() for b in text.split("\n\n") if b.strip()]
    return "".join(f"<p>{html.escape(b)}</p>" for b in blocks) or (
        '<p class="empty">Not yet written.</p>'
    )


def _badges(p: Profile) -> str:
    out = [f'<span class="tag kindtag">{p.kind}</span>']
    out.append(
        '<span class="tag ok">endorsed</span>'
        if p.endorsed
        else '<span class="tag prov">unreviewed</span>'
    )
    if p.kind == PERSON and not p.active():
        out.append('<span class="tag dormant">dormant</span>')
    return "".join(out)


def render_index(profiles: list[Profile]) -> str:
    n_ok = sum(1 for p in profiles if p.endorsed)
    parts = [
        "<h1>LAIR profiles</h1>",
        f'<p class="sub">{len(profiles)} profiles · {n_ok} endorsed · '
        f"{len(profiles) - n_ok} unreviewed. Generated from the group's Slack "
        "history; the markdown files are the source of truth.</p>",
    ]
    for kind, label in ((INSTRUMENT, "Instruments"), (PERSON, "People")):
        group = sorted(
            (p for p in profiles if p.kind == kind),
            key=lambda x: (x.kind == PERSON and not x.active(), x.name.lower()),
        )
        if not group:
            continue
        parts.append(f'<h2 class="sec">{label} ({len(group)})</h2>')
        for p in group:
            blurb = p.abstract.split("\n\n")[0][:180] if p.abstract else ""
            last = p.last_active() or "—"
            parts.append(
                f'<div class="card"><div class="row">'
                f'<a class="name" href="/profiles/{p.kind}/{_slug(p)}">'
                f"{html.escape(p.name)}</a>{_badges(p)}"
                f'<span style="margin-left:auto;color:#9aa0a8;font-size:.82rem">'
                f"last {html.escape(last)}</span></div>"
                f'<div class="blurb">{html.escape(blurb)}</div></div>'
            )
    return "".join(parts)


def _slug(p: Profile) -> str:
    from slackqa.profiles import slug

    return slug(p.name)


def render_profile(p: Profile) -> str:
    parts = [
        '<div class="crumb"><a href="/profiles">← all profiles</a></div>',
        f"<h1>{html.escape(p.name)}</h1>",
        f'<div class="row" style="margin-bottom:1.4rem">{_badges(p)}</div>',
        '<h2 class="sec">Abstract</h2>',
        f'<div class="abstract">{_paras(p.abstract)}</div>',
    ]

    if p.systems:
        chips = "".join(
            f'<span class="chip">{html.escape(s.strip())}</span>'
            for s in p.systems.split(",")
            if s.strip()
        )
        parts += ['<h2 class="sec">Sample systems</h2>', f'<div class="systems">{chips}</div>']

    parts.append('<h2 class="sec">Timeline</h2>')
    if not p.timeline:
        parts.append('<p class="empty">No entries yet.</p>')
    slug_ = _slug(p)
    base = f"/profiles/{p.kind}/{slug_}"
    for e in p.timeline:
        grain = "month" if e.monthly else "year"
        eid = e.period.replace("-", "")
        marks = []
        if e.endorsed_by:
            marks.append(
                f'<span class="tick">endorsed</span> by {html.escape(e.endorsed_by)}'
            )
        if e.edited_by:
            marks.append(f"edited by {html.escape(e.edited_by)}")
        if not marks:
            marks.append("unreviewed")

        parts.append(
            f'<div class="entry {"" if e.monthly else "year"}">'
            f'<div class="period">{html.escape(e.period)}'
            f'<span class="grain">{grain}</span></div>'
            f"<div>{html.escape(e.text)}"
            f'<div class="prov">{" &middot; ".join(marks)}'
            f"<button onclick=\"document.getElementById('en{eid}')"
            f".classList.toggle('hidden')\">endorse</button>"
            f"<button onclick=\"document.getElementById('ed{eid}')"
            f".classList.toggle('hidden')\">edit</button></div>"

            f'<form id="en{eid}" class="mini hidden" method="post" '
            f'action="{base}/entry/{e.period}/endorse">'
            '<input type="text" name="actor" placeholder="your name" required>'
            '<div class="actions"><button class="primary" type="submit">'
            "Endorse this entry</button></div></form>"

            f'<form id="ed{eid}" class="mini hidden" method="post" '
            f'action="{base}/entry/{e.period}/edit">'
            '<input type="text" name="actor" placeholder="your name" required>'
            f'<textarea name="text">{html.escape(e.text)}</textarea>'
            '<div class="actions"><button class="primary" type="submit">'
            "Save entry</button></div></form>"

            "</div></div>"
        )

    slug_ = _slug(p)
    base = f"/profiles/{p.kind}/{slug_}"
    parts += [
        '<div class="warn"><b>Unauthenticated demo.</b> Anyone who can reach this '
        "page can endorse or edit. Every action is recorded with the name given "
        "below, so put your real one.</div>",
        '<div class="actions">',
        f"<button onclick=\"document.getElementById('endorse').classList.toggle('hidden')\">"
        f"{'Re-endorse' if p.endorsed else 'Endorse'}</button>",
        "<button onclick=\"document.getElementById('edit').classList.toggle('hidden')\">"
        "Edit</button>",
        "</div>",

        f'<form id="endorse" class="panel hidden" method="post" action="{base}/endorse">',
        "<label>Your name</label>",
        '<input type="text" name="actor" placeholder="e.g. Dong Chen" required>',
        '<div class="actions"><button class="primary" type="submit">'
        "Endorse this profile</button></div>",
        "</form>",

        f'<form id="edit" class="panel hidden" method="post" action="{base}/edit">',
        "<label>Your name</label>",
        '<input type="text" name="actor" placeholder="e.g. Dong Chen" required>',
        "<label>Abstract</label>",
        f'<textarea name="abstract">{html.escape(p.abstract)}</textarea>',
        "<label>Sample systems (comma separated)</label>",
        f'<input type="text" name="systems" value="{html.escape(p.systems)}">',
        '<div class="actions"><button class="primary" type="submit">Save</button>'
        "</div>",
        "</form>",
    ]

    meta = []
    if p.source:
        meta.append(
            f'Abstract seeded from <a href="{html.escape(p.source)}">the lab page</a>'
        )
    if p.endorsed_by:
        meta.append(f"Endorsed by {html.escape(p.endorsed_by)}")
    if p.updated:
        meta.append(f"Updated {html.escape(p.updated)}")
    if meta:
        parts.append(f'<div class="meta">{" · ".join(meta)}</div>')
    return "".join(parts)


async def index(request: web.Request) -> web.Response:
    store: Profiles = request.app[PROFILES]
    return _page("LAIR profiles", render_index(store.all()))


async def detail(request: web.Request) -> web.Response:
    store: Profiles = request.app[PROFILES]
    kind = request.match_info["kind"]
    want = request.match_info["slug"]
    for p in store.all(kind if kind in (PERSON, INSTRUMENT) else None):
        if _slug(p) == want:
            return _page(f"{p.name} — LAIR profiles", render_profile(p))
    raise web.HTTPNotFound(text="No such profile")


async def as_json(request: web.Request) -> web.Response:
    store: Profiles = request.app[PROFILES]
    out: list[dict[str, Any]] = []
    for p in store.all():
        out.append(
            {
                "name": p.name, "kind": p.kind, "endorsed": p.endorsed,
                "active": p.active(), "last": p.last_active(),
                "abstract": p.abstract, "systems": p.systems,
                "timeline": [{"period": e.period, "text": e.text} for e in p.timeline],
            }
        )
    return web.json_response(out)


def _find(store: Profiles, kind: str, want: str) -> Profile | None:
    for p in store.all(kind if kind in (PERSON, INSTRUMENT) else None):
        if _slug(p) == want:
            return p
    return None


async def endorse(request: web.Request) -> web.Response:
    store: Profiles = request.app[PROFILES]
    form = await request.post()
    actor = str(form.get("actor", "")).strip()
    if not actor:
        raise web.HTTPBadRequest(text="A name is required to endorse.")

    kind, want = request.match_info["kind"], request.match_info["slug"]
    p = _find(store, kind, want)
    if p is None:
        raise web.HTTPNotFound(text="No such profile")

    from datetime import date

    p.endorsed_by = f"{actor} ({date.today().isoformat()})"
    store.save(p)
    await _audit(request, p, "endorse", actor)
    raise web.HTTPFound(f"/profiles/{p.kind}/{want}")


async def edit(request: web.Request) -> web.Response:
    store: Profiles = request.app[PROFILES]
    form = await request.post()
    actor = str(form.get("actor", "")).strip()
    if not actor:
        raise web.HTTPBadRequest(text="A name is required to edit.")

    kind, want = request.match_info["kind"], request.match_info["slug"]
    p = _find(store, kind, want)
    if p is None:
        raise web.HTTPNotFound(text="No such profile")

    changed = []
    abstract = str(form.get("abstract", "")).strip()
    systems = str(form.get("systems", "")).strip()
    if abstract != p.abstract:
        changed.append("abstract")
        p.abstract = abstract
    if systems != p.systems:
        changed.append("systems")
        p.systems = systems

    if changed:
        store.save(p)
        await _audit(request, p, "edit", actor, ", ".join(changed))
    raise web.HTTPFound(f"/profiles/{p.kind}/{want}")


async def _audit(request: web.Request, p: Profile, action: str, actor: str,
                 detail: str = "") -> None:
    """Record the action if a store is attached. The dashboard runs without one
    in tests, and an unrecorded edit is better than a failed one."""
    store = request.app.get(AUDIT)
    if store is None:
        return
    try:
        await store.record_profile_action(p.name, p.kind, action, actor, detail)
    except Exception:  # pragma: no cover - the edit already succeeded
        pass


async def entry_action(request: web.Request) -> web.Response:
    """Endorse or edit a single timeline entry."""
    from datetime import date

    store: Profiles = request.app[PROFILES]
    form = await request.post()
    actor = str(form.get("actor", "")).strip()
    if not actor:
        raise web.HTTPBadRequest(text="A name is required.")

    kind, want = request.match_info["kind"], request.match_info["slug"]
    period, what = request.match_info["period"], request.match_info["what"]
    p = _find(store, kind, want)
    if p is None:
        raise web.HTTPNotFound(text="No such profile")
    entry = p.entry_for(period)
    if entry is None:
        raise web.HTTPNotFound(text=f"No entry for {period}")

    stamp = f"{actor} ({date.today().isoformat()})"
    if what == "endorse":
        entry.endorsed_by = stamp
        detail = period
    else:
        text = " ".join(str(form.get("text", "")).split())
        if not text:
            raise web.HTTPBadRequest(text="An entry cannot be emptied.")
        if text == entry.text:
            raise web.HTTPFound(f"/profiles/{p.kind}/{want}")
        entry.text = text
        entry.edited_by = stamp
        detail = f"{period}: text"

    store.save(p)
    await _audit(request, p, f"entry-{what}", actor, detail)
    raise web.HTTPFound(f"/profiles/{p.kind}/{want}")


PROFILES = web.AppKey("profiles", Profiles)
AUDIT = web.AppKey("audit_store", object)


def attach(app: web.Application, profiles_dir, store=None) -> None:
    app[PROFILES] = Profiles(profiles_dir)
    if store is not None:
        app[AUDIT] = store
    app.router.add_get("/profiles", index)
    app.router.add_get("/profiles.json", as_json)
    app.router.add_get("/profiles/{kind}/{slug}", detail)
    app.router.add_post("/profiles/{kind}/{slug}/endorse", endorse)
    app.router.add_post("/profiles/{kind}/{slug}/edit", edit)
    app.router.add_post(
        "/profiles/{kind}/{slug}/entry/{period}/{what:endorse|edit}", entry_action
    )
